### ISSUE TITLE
Sending additional data on handshake

### ISSUE THREAD

**Issue by whodidthis** [ptaoussanis/sente#110]
Seeing as reauthentication can now be handled with `chsk-reconnect!` would it make sense to allow arbitrary data as a third item on the `:chsk/handshake` event uid/csrf vector? For example sending user roles on login that would enable client side to display whatever features are available to the user.

Not sure how best to implement but maybe picking from a predetermined key on ring request map? https://github.com/ptaoussanis/sente/blob/master/src/taoensso/sente.cljx#L472

**Comment by ptaoussanis** [comment]
Hi there, could you clarify what kind of API you had in mind?

You want clients to receive an event of form ` [:chsk/handshake [<?uid> <?csrf-token> <?arb-data>]]`?

How/where would you expect to set the `<?arb-data>` content? Not sure I follow what you mean about picking from a predetermined key on the Ring request map - could you give an example?

Also, any reason you'd prefer to receive this arb data directly with the handshake rather than with something like:
1. Client receives `[:chsk/handshake [<?uid> <?csrf-token>]]` event, as now.
2. Client's handler for this event issues a `chsk-send!` call to the server requesting any extra arbitrary data.

Does that make sense? Is it important that you avoid the extra roundtrip?

**Comment by ptaoussanis** [comment]
What about this?: https://github.com/ptaoussanis/sente/commit/6ae345ca94821e1f1bd146f73ddecd37533455b1

**Comment by whodidthis** [comment]
Looks good! At first I was thinking sente would have to use a similar "hard-coded" key than csrf and friends (`(get-in ring-req [:session :csrf-token])`) but looks like I can specify those too!

**Comment by ptaoussanis** [comment]
Okay, closing for now. Feel free to reopen if you run into any issues later. Cheers! :-)
