### ISSUE TITLE
CompilerException java.lang.RuntimeException: Unable to resolve symbol: loop_10844

### ISSUE THREAD

**Issue by ptaoussanis** [ptaoussanis/sente#112]
Thanks to @stephenbrady for a detailed report on this issue [here](https://github.com/ptaoussanis/sente/issues/108#issuecomment-77682804).

Simple repro available [here](https://github.com/ptaoussanis/sente/issues/108#issuecomment-77933457).

Cause is [here](http://dev.clojure.org/jira/browse/ASYNC-86).

Until an upstream fix is provided, workaround is to avoid using `[org.clojure/tools.analyzer.jvm "0.6.6"]`; `[org.clojure/tools.analyzer.jvm "0.1.0-beta12"]` should work fine.

**Comment by deaddowney** [comment]
This workaround doesn't do the trick for me.

Caused by: java.lang.RuntimeException: Unable to resolve symbol: loop_10171 in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:7004)
	at clojure.lang.Compiler.resolve(Compiler.java:6948)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6909)
	at clojure.lang.Compiler.analyze(Compiler.java:6481)


lein deps :tree output:

 [com.taoensso/sente "1.4.1" :exclusions [[org.clojure/core.async]]]
   [com.taoensso/encore "1.22.0"]
   [com.taoensso/timbre "3.4.0"]
     [io.aviso/pretty "0.1.16"]
   [org.clojure/tools.reader "0.8.16"]
 [org.clojure/core.async "0.1.0-20150331.185252-1" :exclusions [[org.clojure/tools.analyzer.jvm]]]
 [org.clojure/tools.analyzer.jvm "0.1.0-beta12"]
   [org.clojure/core.memoize "0.5.6"]
     [org.clojure/core.cache "0.6.3"]
       [org.clojure/data.priority-map "0.0.2"]
   [org.clojure/tools.analyzer "0.1.0-beta12"]
   [org.ow2.asm/asm-all "4.1"]

**Comment by ptaoussanis** [comment]
Closing, recent releases of tools.analyzer.jvm should resolve this.
