### ISSUE TITLE
Passing an authentication token in the websocket upgrade request

### ISSUE THREAD

**Issue by danielcompton** [ptaoussanis/sente#135]
I'm trying to use Sente where the Sente server is on one domain, the webapp files are served from another one, and a third server is providing an authentication token. I've got things mostly working, but I'd like to be able to authenticate the user and assign a `uid` from the token when they connect to the channel socket. The Sente server will authenticate the user with a JWT token, not session storage.

It's not clear to me how to pass the token in the initial connection as there doesn't seem to be an extension point for me to pass any more data here: https://github.com/ptaoussanis/sente/blob/v1.4.1/src/taoensso/sente.cljx#L843-L844

Alternatively, am I meant to connect first, then authenticate second? If so, once a client is authenticated, how would I check that every subsequent channel socket message was authenticated and update the `uid` of the connection? It would be much cleaner for this to be part of the ring request, rather than kept in an external store that I have to keep in sync with Sente's connection state. 

I've seen https://github.com/seancorfield/om-sente/blob/master/src/clj/om_sente/server.clj#L112-L119, but don't particularly like having an external auth store, and it also uses Ring session storage to get the `uid`.

It's possible that I'm misunderstanding this entirely, how else would you recommend handling cross domain auth/Sente connections?

**Comment by danielcompton** [comment]
Instead of passing the token in the URL, it would probably be better to pass it in the headers. However there doesn't seem to be a way to specify arbitrary headers either.

**Comment by danielcompton** [comment]
I'm happy to take a crack at a PR for this, but wanted to get your feedback first.

**Comment by estsauver** [comment]
I second this, a mechanism for passing along an auth header would be neat! I'm also using a JWS token, so that would be super convenient.

**Comment by danielcompton** [comment]
@ptaoussanis have you had a chance to look at or think about this? I'm happy to do the work for it but wanted to know your thoughts first.

**Comment by ptaoussanis** [comment]
Sorry, have been quite limited on time/energy recently. Am most likely to be able to respond to a question quickly if it's something that I can grok immediately. 

Any chance you could simplify / rephrase your question so that I don't need to spend too much time trying to understand the relevant bits of your architecture?

What are you using as your uid function?

> I'm happy to take a crack at a PR for this

A PR for what exactly? Could you describe what you're proposing, specifically? The more concrete you can be - the more likely I can get on the same page quickly.

> It's not clear to me how to pass the token in the initial connection as there doesn't seem to be an extension point for me to pass any more data here

Not sure if this is actually relevant/useful to what you're trying to do, but just confirming that you know you can include arbitrary parameters in your URL here (that's what the line you highlighted is for)?
