### ISSUE TITLE
Wrap :chsk/error, :chsk/timeout in a vector

### ISSUE THREAD

**Issue by danielcompton** [ptaoussanis/sente#165]
The default ?reply-fn takes a single argument. If I want to return more information in a `?reply-fn` I need to put it in a vector or map. Sente errors are `:chsk/timeout`, `:chsk/error`, or `:chsk/closed`. This means I can't destructure the arguments from the ?reply-fn directly, and I have to check the value first. 

```clj
(ws/chsk-send!
      [:my-app/event {:more :params}] 5000
      (fn [event]
        (let [ev  (if (keyword? event) event (first event))
              rst (if (keyword? event) nil (rest event))]
          (case ev
            :my-app/success
            nil ;; This is the successful case

            :chsk/timeout
            (do (report-query-error token [event {:message "The server timed out while trying to run that query" :retryable? true}])
                (clean-up-query token))

           ;; e.t.c.
```

Would it make sense to return errors in a vector or map to match the rest of Sente's API design? Alternatively `?reply-fn` could take a variable number of arguments, though I'm not as fond of that design.

**Comment by ptaoussanis** [comment]
Hi Daniel,

> This means I can't destructure the arguments from the ?reply-fn directly, and I have to check the value first.

That's correct, but I'd suggest you could probably be doing it in a slightly more convenient way:

```clojure
(ws/chsk-send!
  [:my-app/event {:more :params}] 5000
  (fn [result]
    (if-not (sente/cb-success?)
      (do ; Error handling...
        )
      (let [[ev rst] result]
        ;; App handling...
        ))))
```

I.e. don't destructure until you've ruled out `:chsk/_` errors. Once you have, you're entirely in control of the data format and can destructure as you like w/o worry.

Does that make sense / help?

**Comment by danielcompton** [comment]
Yep that approach does make sense, and would simplify my code. I'll move to that to clean things up. 

The other benefit I forgot to mention is that passing a vector/map would also allow Sente to send more error context to the callback. For example, at the moment when there is a `:chsk/error` the error is logged to the console, but the callback only gets `:chsk/error` without details on the error. This makes it more difficult for the app writer to take further action based on the error, e.g. sending it to an error tracking server for further analysis.

**Comment by ptaoussanis** [comment]
I'd be open to adding more context if it's useful, but not sure I'm following what context you're thinking of exactly.

The errors that are currently possible are:
:chsk/closed - The channel socket's closed
:chsk/timeout - The request timed out
:chsk/error - Something unexpected happened

The `:chsk/error` type is intentionally a catch-all since it's rare and usu. indicates either a bug in Sente or something else very strange that you shouldn't be branching behaviour against.

:chsk/closed and :chsk/timeout are something that application code might reasonably want special handling for. The remaining catch-all error is just there as a fallback instead of throwing.

If there's some specific `:chsk/error` that's showing up and that application authors might like to deal with, then we could just add a new `:chsk/_` error type to accommodate.

Upgrading these errors to a `[error-id ?data]` form would only be useful if we have something interesting to add as `?data`: do you have something in mind?

**Comment by danielcompton** [comment]
The only extra context available would be the `:chsk/error`. I guess I can see what it's like in production (launching soon), my concern is that if we do get a `:chsk/error` in the wild, it will be hard to know exactly what went wrong.

**Comment by ptaoussanis** [comment]
> my concern is that if we do get a :chsk/error in the wild, it will be hard to know exactly what went wrong

Gotcha. Shouldn't be any need to though, just treat it as you would a timeout. You shouldn't get any of these at all. If you happen to get the odd one, it should be safe to treat as a timeout (likely a random timing or server issue). If you get more than the odd one, you can contact me since it implies a likely bug in Sente, the server, or server adapter. Nothing I can think to include in the context would help you debug on your end.

The approach I'd recommend for good hygiene: always check `cb-success?` against callback replies.
If true, you can be certain your reply is good - handle it as you'd like.
If false, there was a connectivity issue. In most cases all connectivity issues will be handled the same way. On the odd occasions when you care about the difference between a timeout+close, you can match against those. Treat anything else as an unexpected connectivity error.

Does that help / make sense?

**Comment by danielcompton** [comment]
That makes sense, I'll implement those checks and see how it feels in practice. Closing this for now. Thanks for the feedback!

**Comment by ptaoussanis** [comment]
Sure, np. Feel free to reopen if you have any other thoughts/ideas. Cheers :-)
