### ISSUE TITLE
Guidance for closing an unauthorised connection

### ISSUE THREAD

**Issue by danielcompton** [ptaoussanis/sente#172]
What is the recommended way to disconnect an unauthorised Sente connection?

Currently my steps are:

1. Browser Sente opens a connection to Sente server
2. In `:chsk/uidport-open` I check if the connection is authorised.
3. If it is not authorised I send an application level message telling the browser to shut down the connection
4. I setup a timeout for 5 seconds, after which I drop the connection using the (undocumented) `:chsk/close` command.

This feels a little clunky and inelegant. I don't like having to send an application level shutdown message, but if I unilaterally close the connection then the Sente browser client automatically reconnects. Is there a better way to handle this process?

**Comment by ptaoussanis** [comment]
Hey Daniel,

What do you mean by "unauthorized" in this context exactly? And how do these unauthorized connections come to be? Are they established unauthorized or do they start out authorized and lose their authorization somehow in time?

**Comment by ptaoussanis** [comment]
Assuming this is resolved but please feel free to reopen if you're still having trouble.

**Comment by danielcompton** [comment]
Sorry, I missed replying to this.

> What do you mean by "unauthorized" in this context exactly? 

An unauthorised connection would be one where the user is trying to connect as someone that they don't have the auth permissions for.

> And how do these unauthorized connections come to be?

They are created when the client connects to the server.

> Are they established unauthorized or do they start out authorized and lose their authorization somehow in time?

They are established unauthorised, and then we check if they are authorised in `:chsk/uidport-open`. If they are not authorised we want to disconnect them, but we need to send an application level message to achieve this, as if we just close the connection on the server then the client will try to reconnect.

**Comment by ptaoussanis** [comment]
No problem.

One part of your approach I'm not following: `:chsk/uidport-open` triggers only after a client's already got a user-id. In most cases that implies that the client has already been authenticated.

But it sounds like you're issuing a user-id before the user has been authenticated?

Let's start by clarifying a definition since I think that may also be causing confusion:
- If we're talking about logging a user in (checking username+password, etc.) - let's called that **authentication**
- If we're talking about checking whether an authenticated user has access to some particular resource/action - let's call that **authorization**.

As I understand it, you're talking about authentication here rather than authorization right?

How is the client getting a user-id in your case? What is the semantic meaning of the user-id in your case?

**Comment by danielcompton** [comment]
Yep, this is all talking about authentication here.

The user-id-fn is created based on context from the client request, they pass a username, and we look at their IP address in the ring request to make a `uid`. My assumption was that assigning the user id didn't imply authorisation, though now that I think about it, maybe that's the issue?

 If we don't want to/can't authenticate a connection, should we return nil in uid-fn? Or is there some other way to indicate that a user is not authenticated, and to get them to disconnect?

**Comment by ptaoussanis** [comment]
Well, to be clear: issuing a user-id *is* a form of authentication; it's literally assigning an identity to a client. But whatever meaning (e.g. authorization rights) that uid has is entirely up to your application.

Also note that any user-id determined solely using client-side information is inherently insecure (i.e. open to impersonation, etc.). 

Two common/idiomatic authentication approaches:

1. Client starts out without a channel socket at all (i.e. no user-id). Client then goes through a login procedure using Ajax. This sets a `:uid` value in the browser's session. A channel socket is now established with the user-id fn using the `:uid` value in the Ring request's session. All future API requests just need to double check that the requesting uid is authorized for the particular API call.

2. Clients start out with a temporary/dummy/unauthenticated channel socket using a dummy/random/temporary user-id. This uid doesn't authorize anything sensitive. The client can then go through a login procedure using Ajax. As before, that sets a session `:uid`, etc.

So generally speaking a user-id == an authenticated identity. What that identity is authorized to do is up to you. And if you want to upgrade or downgrade a client's authroization abilities, you'll generally want to re-authenticate as a new identity with more/fewer privileges.

Does all that make sense?

This stuff can be a little confusing but it's unfortunately mostly by necessity (internet security can be a little hairy). Sente's default is for the `user-id-fn` to just grab the session `:uid` value. In most cases, the best idea is if you can bend your app to fit to that model since it's secure and flexible. Something using private auth tokens would also be fine if it's operating entirely over HTTPS.

As a general rule though: any form of authentication that's not strictly session based is going to require careful tradeoffs (many of which may directly impact security).

**Comment by danielcompton** [comment]
Using `lein-master`, I was able to download dependencies from central, clojars and a private S3 wagon. I was able to deploy to the private S3 wagon, but I wasn't able to deploy to Clojars. I was able to deploy the same library to Clojars with lein 2.5.3. I got the following error message

```
lein-master deploy
<my private GPG creds printed out here>
java.lang.NullPointerException: null
 at java.io.StringReader.<init> (StringReader.java:50)
    clojure.lang.RT.readString (RT.java:1820)
    clojure.lang.RT.readString (RT.java:1816)
    clojure.core$read_string.invoke (core.clj:3663)
    leiningen.core.user$credentials_fn.invoke (user.clj:143)
    leiningen.core.user$credentials_fn.invoke (user.clj:134)
    clojure.lang.AFn.applyToHelper (AFn.java:152)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invoke (core.clj:630)
    clojure.core$memoize$fn__5479.doInvoke (core.clj:6082)
    clojure.lang.RestFn.invoke (RestFn.java:397)
    leiningen.core.user$resolve_credential$resolve__7011.invoke (user.clj:165)
    leiningen.core.user$resolve_credential.invoke (user.clj:174)
    clojure.core$partial$fn__4527.invoke (core.clj:2494)
    clojure.core.protocols$iter_reduce.invoke (protocols.clj:49)
    clojure.core.protocols/fn (protocols.clj:112)
    clojure.core.protocols$fn__6452$G__6447__6465.invoke (protocols.clj:13)
    clojure.core$reduce.invoke (core.clj:6519)
    leiningen.core.user$resolve_credentials.invoke (user.clj:183)
    leiningen.core.classpath$add_repo_auth.invoke (classpath.clj:67)
    leiningen.deploy$repo_for.invoke (deploy.clj:72)
    leiningen.deploy$deploy.invoke (deploy.clj:197)
    leiningen.deploy$deploy.invoke (deploy.clj:186)
    clojure.lang.Var.invoke (Var.java:379)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invoke (core.clj:632)
    leiningen.core.main$partial_task$fn__6449.doInvoke (main.clj:272)
    clojure.lang.RestFn.invoke (RestFn.java:410)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.RestFn.applyTo (RestFn.java:132)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:632)
    leiningen.core.main$apply_task.invoke (main.clj:322)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:328)
    leiningen.core.main$_main$fn__6515.invoke (main.clj:401)
    leiningen.core.main$_main.doInvoke (main.clj:394)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.lang.Var.invoke (Var.java:379)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invoke (core.clj:630)
    clojure.main$main_opt.invoke (main.clj:316)
    clojure.main$main.doInvoke (main.clj:421)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
```

It doesn't really look like it's related to the clj-http change (at least not directly), but it needs to be checked out.

**Comment by ptaoussanis** [comment]
Closing this for now, please feel free to reopen if there's still anything I can help with :-)

**Comment by theronic** [comment]
How do I assign a uid to a client when they connect?
