### ISSUE TITLE
Request GET /ws timeout after initial handshake

### ISSUE THREAD

**Issue by martinhynar** [ptaoussanis/sente#180]
Hi, I am really lost, any clue is welcome. I use sente 1.6.0 + http-kit 2.1.19. I use only :ajax
- handshake succeeds
- POST requests from client are nicely served

But, periodic `GET /ws?_...` requests timeout even though I see them served on server side. Enabling ring log wrapper gives me:

```
Starting :get /ws?_=1447959914598&client-id=bd27bc63-7372-4336-9bd3-472b633ea324 for 127.0.0.1 {"accept" "*/*", "accept-encoding" "gzip, deflate, sdch", "accept-language" "en-US,en;q=0.8,cs;q=0.6", "connection" "keep-alive", "host" "localhost:8080", "referer" "http://localhost:8080/ui?", "user-agent" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36", "x-requested-with" "XMLHTTPRequest"}

Finished :get /ws?_=1447959914598&client-id=bd27bc63-7372-4336-9bd3-472b633ea324 for 127.0.0.1 in (2 ms) Status: 200
```

There must be something I missed and it pisses me off because otherwise sente is working like a charm (great work indeed).

**Comment by danielcompton** [comment]
Hey @martinhynar is this happening running the example project? If not, can you try it there?

**Comment by martinhynar** [comment]
Well, things are getting interesting.

Example project is running fine when unchanged. Those 'GET pings' succeed all after 10s. This is exactly the delay in broadcaster loop. And data from this loop are in responses for these GETs.

But, when I disable that broadcaster loop, so no server->client pushes, I see the same behavior. 'GET pings' timeout after 25s.

**Comment by martinhynar** [comment]
Adding similar 'pong' server broadcaster to my app resolved the timeouts, but that does not seem right to me.

**Comment by ptaoussanis** [comment]
Hey there, sorry for the delay replying - have been travelling.

Sente automatically+intentionally times out and re-establishes Ajax long-polling connections that haven't seen activity in a while. The particular timeout is controlled by the client-side `make-channel-socket!` `:lp-timeout-ms` option (defaults to 25 seconds).

Is that perhaps what you're talking about? If so, what you're seeing is by design and not a problem.

You can increase the timeout if you like, but please note that the default is there to help work around browser and proxy defaults which'll often kill a request that's been idle too long. 25s is a reasonable balance between efficiency and reliability in different environments.

**Comment by ptaoussanis** [comment]
Just for clarity: the example project's broadcasting loop is causing constant activity meaning that no timeouts ever occur. If any activity occurs in < the timeout window, you'll never see timeouts. Though seeing timeouts isn't harmful.

**Comment by ptaoussanis** [comment]
Assuming this is resolved but please feel free to reopen if you're still having trouble.

**Comment by martinhynar** [comment]
Thanks for explanation. Those timeouts ignited curiosity in me like there was some polling that I forgot to handle on server side. Now the purpose is clear.

**Comment by ptaoussanis** [comment]
No problem, happy I could help :-)
