### ISSUE TITLE
Add support for other Clojure-side web servers (i.e. besides http-kit)

### ISSUE THREAD

**Issue by ptaoussanis** [ptaoussanis/sente#2]
This shouldn't be too hard (there's only a small surface area that actually interacts with http-kit) but will require potential servers to expose a sensible API that we can use.

Don't have a lot of time to look into this myself atm, so assistance would be welcome:
 * What server(s) should we target? [This](https://github.com/ptaoussanis/clojure-web-server-benchmarks) might be a useful starting point?
 * What API does each expose?
 * Suggested abstraction to encapsulate any API differences?

Otherwise any other thoughts/suggestions very welcome! Feel free to ping me with any questions :-)

**Comment by tobias** [comment]
I've done some work on creating a Channel abstraction for Sente, and
using that abstraction to support both http-kit and Immutant 2. I
realize you removed the 'pull-requests-welcome!' tag, but I'm hoping
we can have a discussion about my implementation, and see what it
would take to get it (or something similar merged in).

The full PR is https://github.com/ptaoussanis/sente/pull/101.

The real changes are in `interfaces.cljx` and both namespaces in
`sente/server/`. The changes to `sente.cljx` to use the Channel
procotol are extensive, but should result in no behavioral changes (as
far as I can tell from playing with the example app). I tested with
http-kit, Immutant embedded (which uses undertow directly), and
deploying an Immutant war to the WildFly application server (which
uses servlets inside undertow).

The differences between the new Sente Channel protocol and http-kit's
Channel protocol are:

* `with-channel` has been replaced with `as-channel`, which is a
  function that takes callbacks instead of a macro that binds the
  channel to a symbol. In http-kit's case, the channel is already
  available when `with-channel` starts to evaluate its body, but
  Immutant cannot provide that same mechanism, but instead passes the
  channel to an `on-open` callback when it is ready. Sente's
  `as-channel` adopts that same approach, and the http-kit
  implementation uses `with-channel`, and just calls the `on-open`
  immediately.
* `send!` no longer closes http streams automatically - you have to
  explicitly pass a falsey value for the `close?` parameter.

The `as-channel` function isn't part of a protocol, since there are no
objects that directly represent a running server (starting an http-kit
server returns a stop function, starting an Immutant server returns a
map). Instead, `as-channel` is a regular function with a default
implementation that throws. Implementations (currently in
`servers/http_kit.clj` and `servers/immutant.clj`) alter the var root
of `as-channel` (via `provide-as-channel!`) with a function that does
the correct thing for that particular server. `sente.cljx` requires
both of these namespaces, but they are guarded by the `with-import`
macro to only code that will work based on which server is currently
on the classpath.

Other changes include:

* the `IAsyncHTTPServer` was removed, since it's not used by this
  implementation
* the dependence on http-kit was removed from `project.clj`. Users
  would be responsible for having a recent enough http-kit dependency
  in their own application.
* the example application has been modified to use either Immutant or
  http-kit, just by adjusting commented lines in `project.clj` and
  `my_app.cljx`.

I haven't looked at what it would take to support any other servers
(Jetty, etc), but hopefully the protocol is general enough to be
adapted to them.

This is a first cut at solving this problem, I'm happy do discuss it
and make any changes necessary to have this be part of the next Sente
release. I updated the docstrings in sente.cljx to reflect these
changes, but haven't yet made any changes to the README.

And if you would prefer to have channel abstraction and the Immutant
implementation as separate PR's, I can do that as well.

**Comment by tobias** [comment]
I forgot to mention that this depends on an [Immutant API](https://projectodd.ci.cloudbees.com/job/immutant2-incremental/449/artifact/target/apidocs/immutant.web.async.html) that isn't yet in an official release, only incremental builds, so it may change some before a release. If the API does change, it should only affect `servers/immutant.clj`.

**Comment by ptaoussanis** [comment]
Closing here since we can continue any Immutant discussion at #101 and I've since added #102 for any other servers.

Busy working on a merge for #101.
