### ISSUE TITLE
Ajax auto-fallback doesn't work when client supports WebSockets but handshake fails

### ISSUE THREAD

**Issue by danielcompton** [ptaoussanis/sente#201]
We had a situation where one of our users was behind a corporate proxy. They weren't able to make unencrypted websocket connections. The connection was failing with this message in their browser console:

```
 Connection to 'ws://<url>' failed: Establishing a tunnel via proxy server failed.
```

Sente has fallback to AJAX, but it seems like this is only used if the browser doesn't support WebSocket APIs, rather than checking if the WebSocket connection can be established or if the network topology stops it. 

Debugging this error was quite difficult because Sente doesn't provide an error callback when creating the websocket, instead it just logs it with Timbre, so we had no way of handling the error further. What do you think about adding an error callback here? Also, what are your thoughts about doing a more sophisticated fallback which detects errors where the network doesn't support WebSockets?

We fixed this by moving to HTTPS ourselves, but I think the issue itself is still valid, I can imagine a more sophisticated SSL proxy which could do the same thing.

**Comment by ptaoussanis** [comment]
Hi Daniel, thanks for the report.

You're correct about the cause: the current behaviour is to fall back to Ajax only if the client-side WebSocket creation fails; not if the WebSocket handshake doesn't succeed for whatever reason.

The best solution isn't immediately obvious to me since the handshake can also fail due to temporary network conn. issues, due to temporary server downtime, etc.

Options incl. trying to detect specific errors like this one for special handling, and falling back on handshake errors (any cause) but then doing some kind of backoff-retry to upgrade the chsk back to WebSockets.

Will need some time to think over this + schedule a fix. Ideas welcome.

**Comment by danielcompton** [comment]
It's probably worth looking at how other websocket libraries like socket.io and co handle this.

**Comment by ptaoussanis** [comment]
A good idea; could I possibly ask you to check if you have time?

**Comment by danielcompton** [comment]
Sure thing :)

**Comment by ptaoussanis** [comment]
Thanks.

Thought about this a little in the meantime; may actually be quite straight-forward: if the client can't create a WebSocket (=> no browser support), fall back to Ajax permanently (= current behaviour).

If the client *can* create a WebSocket but the handshake fails for any reason (1 attempt), fallback to Ajax and start an exp-backoff upgrade attempt. If any WS handshake request ever succeeds, note it and adjust the retry logic.

Just have my hands full atm but will try make this a priority when I have some free time again.

**Comment by ptaoussanis** [comment]
Hey Daniel,

Thought about this some more. Given how rare the error is (and it'll hopefully become increasingly rare as more people switch to using HTTPS), adding general-purpose auto down/up grade logic seems like it might be excessive - esp. since this may turn out to be the only possible case where auto down/up grade is actually useful.

Two options come to mind then:
1. Someone looks into this particular error to confirm how it could be reliably identified across all browsers via the WebSocket's `onerror` handler; and we just add handling for that special case.
2. Sente just publishes WebSocket `onerror` messages and shifts the burden to Sente users who aren't on https + want to support these users.

Would prefer the first, but don't the onerror docs I've found weren't very helpful so would need to dig + don't have time for that myself atm.

Are you still interested in this issue?

**Comment by danielcompton** [comment]
Still interested in this issue, but head down at the moment. Will try to come back to it soonish though :)

**Comment by ptaoussanis** [comment]
Hi @danielcompton, just a heads-up that this has unexpectedly become relevant to a project I'm busy working on; will likely take care of it myself tomorrow.

Cheers :-)

**Comment by nha** [comment]
I think one of the reasons of the socket.io rewrite/split (with engine.io) is to make the connection upgrade from polling/ajax to websocket to prevent this kind of scenario.

This has the benefit of:
- starting the connection faster since there is no need for handshake etc. (also I think it can take some time to properly detect a handshake failure)
- being more reliable since the switch to websocket happens only after it is properly established

**Comment by danielcompton** [comment]
socket.io's method has a big problem if you're [sitting behind an Elastic Load Balancer](http://stackoverflow.com/a/14736178), as there is no guarantee (AFAIK) that your first request will go to the same server as the second. While there are things you can do to work around this, it's more complicated than what Sente does know. Making a single HTTP GET 101 avoids this problem.

**Comment by ptaoussanis** [comment]
Okay still need to test the current strategy, but in principle should have what we need to make this work with v1.9.
