### ISSUE TITLE
Aleph adapter

### ISSUE THREAD

**Issue by ztellman** [ptaoussanis/sente#208]
I'm creating this to take comments out of the other, mostly unrelated issue.

I started on https://github.com/ztellman/sente, but got stuck because both of the adapters seem to rely on some hybrid websocket/HTTP streaming body mechanism that doesn't seem explicitly specified anywhere.  I can dig into the code, but if you can point me to any documentation for the sente protocol, that would make this easiest for me (and any future adapter authors).

**Comment by ptaoussanis** [comment]
Hey Zach,

> if you can point me to any documentation for the sente protocol, that would make this easiest for me (and any future adapter authors).

Documentation's at https://github.com/ptaoussanis/sente/blob/master/src/taoensso/sente/interfaces.cljx, and there's some example adapters at https://github.com/ptaoussanis/sente/tree/master/src/taoensso/sente/server_adapters

Not sure I follow what you're asking exactly, could you possibly rephrase? Is there something in the docs there that's unclear? Not familiar enough with Aleph to comment directly on your implementation w/o more context, sorry.

> I started on https://github.com/ztellman/sente

Please note that this fork's a little old (1.7.0 vs master at 1.81). Some interface names and docstrings were updated in 1.8 to be clearer which might help?

Looking forward to getting an Aleph adapter in, cheers :-)

**Comment by Frozenlock** [comment]
@ztellman any update on the adapter?

**Comment by ptaoussanis** [comment]
Closing for now, please feel free to reopen if there's any new updates - cheers :-)

**Comment by ztellman** [comment]
That's fair, I'll get to it soon, hopefully.

**Comment by morgancmartin** [comment]
Hi all. I am putting a project together using aleph and sente. I am using the aleph server adapter referenced in the sente docs.

My issue is that when aleph attempts to initialize its websocket connection with the server, an error is thrown by `aleph.http.server/initialize-websocket-handler` stating that "java.lang.ClassCastException: clojure.lang.PersistentHashMap cannot be cast to aleph.http.core.NettyRequest."

On the surface this seems like a pretty straightforward error, but after a couple of days of toying around in the aleph.http, and the sente/aleph adapter, I am ready to check in for some guidance.

I am fairly new to Clojure, otherwise I would continue forging ahead alone. Any help would be much appreciated. Fuller code samples and stacktraces available upon request. And thanks very much @ztellman and @ptaoussanis for the awesome libraries.

**Comment by morgancmartin** [comment]
Hey guys, you can disregard my last comment, I figured out the issue (and it was unrelated to aleph, sente or the adapter.) Turns out it was just a silly mistake on my part. I was using a separate server while I was getting figwheel up and running and didn't realize I was still using it instead of Aleph to receive the ws handshake. Pretty dumb, but in case anyone else somehow makes the same mistake, that's what happened.

Cheers and Merry Christmas guys. Thanks again for all the hard work you put into these libraries, they're truly top notch.

**Comment by ztellman** [comment]
Glad you were able to figure it out. Happy holiday tinkering.

**Comment by ptaoussanis** [comment]
@morgancmartin Hi Morgan, no problem - thanks for the update! Cheers and happy new year :-)
