### ISSUE TITLE
Using sente with Reactjs native breaks when trying to get window location

### ISSUE THREAD

**Issue by jlo1** [ptaoussanis/sente#218]
When trying to bundle a react native project using sente, the call to `make-channel-socket!` breaks. The source code attempts to call `enc/get-window-location`, but I’m getting this error `undefined is not an object (evaluating ‘taoensso.encore.get_window_location.call')`. 

Is the call to get win-location necessary if we specify the path and host ourselves? (Looking at https://github.com/ptaoussanis/sente/blob/a884c90169414ae9f1238dfbe7852693d1505e6c/src/taoensso/sente.cljx#L1061)

**Comment by ptaoussanis** [comment]
Hi there, thanks for the report. This is something I'd like to rectify. Will try take a look when I have some free time, otherwise you might be able to help speed this along with a PR.

Have you confirmed that the window location call is the only problem running on Reactjs native?

Thanks, cheers :-)

**Comment by jlo1** [comment]
Simply adding `[com.taoensso/encore "2.49.0"]` to project dependencies worked fine due to changes in this `encore` commit: https://github.com/ptaoussanis/encore/commit/b869ab3d5d01e313cfd946b379ce7ebc73779f6a

**Comment by ptaoussanis** [comment]
Yeah, that's the commit that did it. Your confirmation was helpful since I couldn't recall if anything else might turn out to be a problem.

How's Sente working with React.js otherwise? Working well?
