### ISSUE TITLE
How to close sente session?

### ISSUE THREAD

**Issue by mssilpa** [ptaoussanis/sente#226]
I am trying to do a login application with session.now i have done with login and i just tried to do log out but its not working. What i need is to delete the session and redirect to login page. The session uid is deleted from session-map as follows:
` (defn delete-token   [uid] (swap! session-map dissoc uid) )`
but iam not able to redirect to login page. what should i do?

**Comment by ptaoussanis** [comment]
Hi there,

Not sure I understood all of that, but sounds like you're looking for help understanding how to delete a Ring session? That's not really something that's specific to Sente, so would recommend Googling for something like "how to delete clojure ring session", am sure you should be able to find some examples.

Hope that helps, best of luck! :-)

**Comment by mssilpa** [comment]
i have gone through this example "https://github.com/seancorfield/om-sente".
In this they are not mentioned how to do logout.

**Comment by ptaoussanis** [comment]
Sorry, am not familiar with the example there.

If it's using standard Ring sessions then I would suggest Googling for something like "how to delete clojure ring session".

Otherwise I would suggest asking at https://github.com/seancorfield/om-sente.

Sorry I couldn't be more help! Very busy atm, trying to prioritize open-source efforts.

**Comment by mssilpa** [comment]
ok.Thanks
