### ISSUE TITLE
Multithreading question

### ISSUE THREAD

**Issue by amakurin** [ptaoussanis/sente#227]
Is it correct to say that if we have multiple connections, and each of them are handled by underlying server in a separate thread, then sente will sync all messages of these connections by one channel (Meaning ch-recv created on make-channel-socket-server!) in one thread?  I mean that messages will be ordered and handled in series, but not in parallel.

**Comment by danielcompton** [comment]
@amakurin I'm not 100% sure I understand your question, but I'll give it a go. The default Sente project uses a single go-loop to handle all web socket messages. This means that messages are handled in the order they are received, one at a time. 

There are a few things you could do here to speed things up (and I have been thinking about this myself). Depending on your constraints, you could `pipeline` the go-loop so that up to (say) 20 messages could be in flight. This would raise the possibility of out of order processing of messages. A different approach would be to partition your users in some way (by user id, by company id, e.t.c.) and create one go-loop per partition.

Hope that helps, Peter may correct me if I've got any of this wrong.

**Comment by amakurin** [comment]
@danielcompton thanks for the answer. I guess, you understand my question right. But list of possible solutions is secondary for me right now. First i need to fix the fact that we handle messages in series, one by one, one at a time. And looking at the source i guess that you are right.
After that i think that timeout for one particular client is not a such big problem. But,say, 1000 sequential messages awaiting processing - could be. If we have e.g. 100 ms on request, then we cannot do more then 10 req per second without additional parallelism (we already discard one by directing all messages to single channel). Are these statements correct or i'm missing something? Actually estimation of rate per second is most important part for me right now. If it is correct then looks like none of proposed solutions allow to speed up to, say, 500 req/sec, right?

**Comment by danielcompton** [comment]
This is [queueing delay](https://en.wikipedia.org/wiki/Queuing_delay). If you are only able to process one message every 100ms and you get 500/second then your buffer will quickly grow and you'll drop messages on the floor. You have a few options:

1. Do less work in your handler so it takes less time to process a single message
2. Run more instances of your app with a load balancer so each one gets fewer messages to handle.
3. Immediately acknowledge the message and put it onto your own work queue that is parallelised
4. Parallelise the message handling Sente does by providing a different `chsk-router`

The raw limit on how many messages a second you can handle is the overhead involved in core.async taking and putting values on a channel, and Sente replying (or you can even disable replies if you want). This is comparatively tiny. Looking at our metrics I find we have a 50%ile latency of 0.5ms, and 99%ile latency of 30ms. This should give you some idea of the possibilities. Also, don't forget that Sente keepalive pings are also messages that need to be processed (though they are extremely fast to process).

**Comment by ptaoussanis** [comment]
Hi Alexey, Daniel, will try clarify quickly:

1. Your Sente web server of choice accepts incoming web requests using its own strategies for threading, ordering, etc. and dispatches the requests to Sente.

2. Sente puts relevant requests (as Sente event messages) into a single channel for processing, as it receives them. I.e. they'll be in order if the web server above dispatched them in order.

3. From here it's intentionally, entirely up to you re: how to handle the queued event messages.

The default chsk router is one option. It just uses a `go-loop` to take event messages from the queue and pass them to your handler function (usu. a multimethod).

If your handler is blocking, then this'll mean that your events will indeed be handled sequentially, one at a time. And your throughput will be limited by handler processing time.

More commonly, you'll want your handler to do work through a future, thread pool, or other async/queuing mechanism of your choice. Clojure offers a lot of great choices here, so Sente intentionally stays out of the way of making choices for you.

Some kinds of events you might like to queue, others you might like to run on a future, others you might like to queue on an agent, etc. What you choose here will determine what kind of ordering you get.

Does all that make sense?

**Comment by amakurin** [comment]
Yep, thanks, Peter. Thanks, Daniel. One more question. It seems that the optimal strategy will be to minimize resources (threads) taken by underlying web server, (e.g. immutant if it provides such config options). And maximize parallelism on the handler side. Right?

**Comment by ptaoussanis** [comment]
That's sort of a long topic, but short of it is: wouldn't expect you to need to change anything about your web server's threading. Most servers will run just fine w/ default config.

**Comment by amakurin** [comment]
Yep, i already have completed a couple of projects with sente with http-kit and immutant, and it was fine with defaults, when there was not big load. Now i'm projecting sente based module and just thinking about a possible strategy, posible ways to optimize message handling IF the load will be increased, with minimum (ideally, avoiding) code rewrite. Of course such optimization has a limit. Anyway i understood you. Thanks.

**Comment by ptaoussanis** [comment]
Understood. Generally speaking, you should be fine with your server defaults. If you do happen to start observing problems later, that'd be the best time to adjust settings since you'll know exactly what the problems are. Trying to anticipate them now will be tricky/inaccurate.

Sente doesn't tie you to any decisions that'll be hard to undo later. If you later want to tune servers, or adjust how you pull from the Sente message channel, or adjust how/where you lean on parallelism/caching/whatever. - that's all pretty much easy to do.

Best of luck, cheers! :-)
