### ISSUE TITLE
Calculate RTT for :chsk/ws-ping messages

### ISSUE THREAD

**Issue by danielcompton** [ptaoussanis/sente#272]
It would be helpful for monitoring to see the round trip time for ping's (ping from server to client and reply to server again) to detect when clients have slow connections or there are other network issues. I don't have a really concrete design in mind, but here are a few thoughts:

* This would probably require a sequence number on pings to correlate them
* It's probably unnecessary to calculate this for all users all the time, it may be better to be able to sample them
* This should be optional, as it probably incurs some overhead
* I'm not sure where this info should go, on the connected uid's map?
* I'm not sure what should be recorded? Do we record raw values, or present the user with summary statistics
* Do we store this in a core.async dropping buffer, or some other limited size buffer?

**Comment by ptaoussanis** [comment]
Hi Daniel,

Any particular reason you don't just take this measurement yourself, in the particular way you'd like + makes sense for your application? For example, just send a client->server request and measure the time to respond?

I.e. is there a reason this needs to be a part of Sente core?

**Comment by danielcompton** [comment]
Not particularly, other than that there's already a ping message being sent. Probably fine to be external to Sente though.

**Comment by ptaoussanis** [comment]
Complecting RTT with the ping could lead to trouble though, most obviously: the ping (by design) isn't always sent if there's been other connection activity.

Would also suggest that the number of (valid) design questions you insightfully raised might be an indication that RTT would better be left to application authors so that they can decide what fits best for their particular requirements. Does that make sense?

**Comment by danielcompton** [comment]
Yep, I had that thought too, when I thought more about when pings are sent.
