### ISSUE TITLE
Arbitrarily disconnect client via client-id or user-id?

### ISSUE THREAD

**Issue by bago2k4** [ptaoussanis/sente#302]
Hi,
first let me thank you for the great library.
Is it possible to force a client to disconnect from the server?
Since i use a JWT authentication and in normal http call i use the headers to pass it this is not possible with WS. So i would like to exchange the JWT with a WS message after the handshake and force the client to disconnect if necessary (expired or forged JWT). I know i can reply to the client and have it disconnects but the client is javascript and the code could be manipulated.
Thanks

**Comment by ptaoussanis** [comment]
Hi there,

> Hi, first let me thank you for the great library.

You're welcome, thanks for saying so!

> the client is javascript and the code could be manipulated.

So that's indeed the dominant issue here, we can't ever trust the client. As a result, _all_ requests must always be authenticated in a secure way (e.g. auth by secure session cookie). But once this is the case, the need to disconnect a misbehaving client is significantly reduced since the client can't actually do much besides waste a connection (possible vector for DDOS, etc.).

If the wasted connection is an issue, then you'll need to (as you suggest) disconnect from the server side. How to do this will vary based on your http server.

Hope that helps?
