### ISSUE TITLE
Cannot JSON encode object of class: class org.httpkit.server.AsyncChannel

### ISSUE THREAD

**Issue by reedlaw** [ptaoussanis/sente#76]
I'm a Clojure beginner and it's probably some basic mistake, but I've been struggling to get a websocket connection in my Luminus project. Here's the stack trace:

```
Tue Sep 23 05:02:56 EDT 2014 [worker-4] ERROR - GET /chsk
com.fasterxml.jackson.core.JsonGenerationException: Cannot JSON encode object of class: class org.httpkit.server.AsyncChannel: /0:0:0:0:0:0:0:1:3000<->/0:0:0:0:0:0:0:1:59952
    at cheshire.generate$generate.invoke(generate.clj:147)
    at cheshire.core$generate_string.invoke(core.clj:32)
    at cheshire.core$generate_string.invoke(core.clj:19)
    at ring.middleware.format_response$wrap_format_response$fn__15771.invoke(format_response.clj:184)
    at ring.middleware.multipart_params$wrap_multipart_params$fn__15255.invoke(multipart_params.clj:118)
    at noir.validation$wrap_noir_validation$fn__15329.invoke(validation.clj:155)
    at noir.cookies$noir_cookies$fn__15376.invoke(cookies.clj:72)
    at ring.middleware.cookies$wrap_cookies$fn__13357.invoke(cookies.clj:156)
    at noir.session$noir_flash$fn__13573.invoke(session.clj:158)
    at ring.middleware.flash$wrap_flash$fn__13498.invoke(flash.clj:35)
    at noir.session$noir_session$fn__13559.invoke(session.clj:109)
    at ring.middleware.session_timeout$wrap_idle_session_timeout$fn__13515.invoke(session_timeout.clj:25)
    at ring.middleware.session$wrap_session$fn__13478.invoke(session.clj:98)
    at org.httpkit.server.HttpHandler.run(RingHandler.java:91)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

I get that as soon as I do `lein run`. From the browser I get `Firefox can't establish a connection to the server at ws://localhost:3000/chsk.`. I've tried `lein repl` as well but get the same error. The `example-project` works fine, so I know it's my own code, just not sure how to debug this.

I've uploaded my project [here](https://github.com/reedlaw/room).

**Comment by pkvov** [comment]
i had the same problem.   and i found it conflicted with ring.middleware.format.wrap-restful-format.
is there a plan to resolve the conflicts start with ring.midlleware.****.  
thanks && appreciate your wonderful library
```
32  (-> handler
33      (wrap-authorization auth/auth-backend)
34      (wrap-authentication auth/auth-backend)
35      (wrap-idle-session-timeout
36       {:timeout (* 60 30)
37        :timeout-response (redirect "/")})
38      (wrap-restful-format :formats [:json-kw :edn :transit-json :transit-msgpack])
39      (wrap-defaults (-> site-defaults
40                         (assoc-in [:session :store] (memory-store session/mem))
41                         (assoc-in [:security :anti-forgery] true)))
42      ;;(wrap-internal-error :log #(timbre/error %))
43      ))
```

**Comment by mcferren** [comment]
Hi @ptaoussanis @clojure @necons @neo4j

Could you please elaborate on your answer and perhaps offer some suggestions for Cheshire alternatives? This place is the only place on the internet where I could ind reference to this error:

# Exception: com.fasterxml.jackson.core.JsonGenerationException: Cannot JSON encode object of class:

I have this as my wrapper because I am making cors POST & GET requests and I need to return JSON from my controller.clj

**(def app 
  (-> (handler/api app-routes)
      (middleware/wrap-json-body {:keywords? true})
      (middleware/wrap-json-response)
      (wrap-cors routes #"^http://localhost:9000$")))**

Below are the libraries referenced in my controller.clj

**(ns recursiftion.controller
  (:use [ring.adapter.jetty :only [run-jetty]]
        [recursiftion.websocket :only [wamp-handler]]
        [recursiftion.config :only [conf]]
        )
  (:require [compojure.core :refer :all]
            [compojure.handler :as handler]
            [compojure.route :as route]
            [clojure.java.io :as io]
            [ring.util.io :refer [string-input-stream]]
            [ring.util.response :as resp]
            [ring.util.response :refer [response]]
            [ring.middleware.json :as middleware]
            [ring.middleware.cors :refer [wrap-cors]]
            [environ.core :refer [env]]
            [cheshire.core :refer :all]
            [recursiftion.model :as model]
            [monger.json]
            [clojure.pprint :refer [pprint]]))**

Here is my POST endpoint code in my controller.clj

  **(POST "/node/create" request
      (let [node_object (or (get-in request [:params :data])
                            (get-in request [:body :data])
                            "1ROUTER_ERROR")]
        {:status 200
         :headers {"Content-Type" "application/json"}
         :body (recursiftion.model/createNode node_object)
        }
  ))**


Here are the referenced libraries that pass through my model and are found in a dao_graph.clj

**(ns recursiftion.dao_graph
  (:require [clojure.string]
            [clojurewerkz.neocons.rest        :as nr]
            [clojurewerkz.neocons.rest.cypher :as cy]
            [clojure.pprint :refer [pprint]])
  (:import [org.bson.types.ObjectId])
  )**

Here is the definition of the function that is invoked inside dao_graph.clj:

(defn create-node LEFTBRACKET   nodeobj    RIGHTBRACKET
  (let LEFTBRACKET   _nodeobj nodeobj   RIGHTBRACKET
          (cy/tquery conn create-node { :_nodetype (get-in _nodeobj [:type]) })))

And here is the cypher query that returns a map with "..." as its keys

**(def create-node "CREATE (m:{_nodetype})
                             RETURN M;")**

**Comment by ptaoussanis** [comment]
> Hi @_ptaoussanis @_clojure @_necons @_neo4j @_michaelklishin

Please consider whether this is really the most appropriate avenue for getting help on this issue?

**Comment by fasiha** [comment]
@mcferren you're running into the same issue as #123 except instead of `wrap-restful-format` your problem is probably being caused by `wrap-json-response`. But the problem is the same: you're applying application middleware like JSON response encoding to Sente's routes.

A simple algorithm: 
1. require `[compojure.core :refer [GET POST defroutes routes]]`, specifically [`routes`](http://weavejester.github.io/compojure/compojure.core.html#var-routes).
1. Use `routes` to  split up Sente's routes from your app's routes:
```
(defroutes my-routes
  (GET "/hi" [] (str "hi ")))
(defroutes sente-routes
  (GET  "/chsk" req (ring-ajax-get-or-ws-handshake req))
  (POST "/chsk" req (ring-ajax-post                req)))
(def handler (routes 
               (-> #'sente-routes
                   ring.middleware.keyword-params/wrap-keyword-params
                   ring.middleware.params/wrap-params)
               (-> #'my-routes
                   (wrap-restful-format ,,, )
                   (wrap-defaults ,,, site-defaults))))
```
The middlewares for Sente will be applied to the application routes `my-routes` as well, but `wrap-keyword-params` and `wrap-params` are most likely harmless there.
